version = "0.2.1"
content_dir = "content"

[html.spine]
vertebrae = ["*.typ"]

[pdf.spine]
title = "Hacker Archives"
vertebrae = ["index.typ"]
merge = true

[epub.spine]
title = "Hacker Archives"
vertebrae = ["index.typ", "about.typ"]
